spring:
  profiles:
    active:
    - dev
---
server:
  port: 4002 #注册中心占用7001端口,冒号后面必须要有空格
spring:
  profiles: dev
  application:
    name: configoper4001

---
server:
  port: 4001 #注册中心占用7001端口,冒号后面必须要有空格
spring:
  profiles: test
  application:
    name: configoper4001
